version: "3.3"
services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
    image: postgres
    container_name: wisedb
    networks: 
      - wisenet
  web:
    ports:
      - "8081:8081"
    image: natanaelsimoes/wiseweb
    container_name: wiseweb
    depends_on:
      - postgres
    networks: 
      - wisenet
  
networks:
  wisenet:
    driver: "bridge"

  
